services:
  postgres:
    image: "leaf-etl-postgres"
    container_name: "leaf-etl-postgres"
    environment:
      POSTGRES_DB: "leaf-etl"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - leafdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  leafdb:
    external: true
